apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: missym2-k8s-com-tls
spec:
  secretName: missym2-k8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: missym2-k8s.com
  dnsNames:
    - missym2-k8s.com
    - www.missym2-k8s.com
  acme:
    config:
      - http01:
          ingressClassd: nginx
        domains:
          - missym2-k8s.com
          - www.missym2-k8s.com